### ISSUE TITLE
About the configs of preprocessing 3D semantic training data

### ISSUE THREAD

**Issue by haibo-qiu** [scannetpp/scannetpp#20]
Hello, thank you very much for your outstanding work and for sharing your code as open source.

When I was preparing the 3D semantic training data using the following configurations, I couldn't locate the path of the `mapping_file`. As far as I understand, this file is responsible for defining the mapping relationships between raw labels (1.5+) and benchmark classes.

https://github.com/scannetpp/scannetpp/blob/36051daccf9d76224fc4183ae7824d8ba462f62b/semantic/configs/prepare_training_data.yml.template#L1-L16

However, after downloading the entire dataset ( in `DATA_ROOT`), I couldn't find a mapping file in either the dataset or this repository. I would greatly appreciate your assistance with locating this file.
```
DATA_ROOT
       └── data
       └── metadata
       └── splits
```

Furthermore, regarding the other paths , am I correct about the following configurations?
```yaml
data_root: DATA_ROOT/data
labels_path: DATA_ROOT/metadata/semantic/semantic_classes.txt
instance_labels_path: DATA_ROOT/metadata/semantic/instance_classes.txt
```

Thank you for your help in advance!
